import { ProjectCard, type PublicProject } from '@/Components/public/ProjectCard';
import { Button } from '@/Components/ui/button';
import PublicLayout from '@/Layouts/PublicLayout';
import { Head, Link, router } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';

type FilterOption = { name: string; slug: string };
type Page = { data: PublicProject[]; links: { url: string | null; label: string; active: boolean }[] };

export default function ProjectsIndex({ projects, categories, technologies, filters }: { projects: Page; categories: FilterOption[]; technologies: FilterOption[]; filters: { search?: string; category?: string; technology?: string } }) {
    const [search, setSearch] = useState(filters.search ?? ''); const [category, setCategory] = useState(filters.category ?? ''); const [technology, setTechnology] = useState(filters.technology ?? '');
    const submit = (event: FormEvent) => { event.preventDefault(); router.get(route('projects.index'), { search, category, technology }, { preserveState: true, replace: true }); };
    return <PublicLayout><Head title="Proyek" /><section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><p className="text-sm text-accent">Selected & academic work</p><h1 className="mt-3 max-w-3xl font-heading text-5xl font-semibold">Proyek dan studi kasus</h1><form onSubmit={submit} className="mt-10 grid gap-3 rounded-xl border bg-surface p-4 md:grid-cols-[1fr_220px_220px_auto]"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari proyek..." className="min-h-11 rounded-md border bg-background px-3" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-md border bg-background px-3"><option value="">Semua kategori</option>{categories.map((item) => <option key={item.slug} value={item.slug}>{item.name}</option>)}</select><select value={technology} onChange={(event) => setTechnology(event.target.value)} className="rounded-md border bg-background px-3"><option value="">Semua teknologi</option>{technologies.map((item) => <option key={item.slug} value={item.slug}>{item.name}</option>)}</select><Button type="submit">Terapkan</Button></form>{projects.data.length ? <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{projects.data.map((project) => <ProjectCard key={project.id} project={project} />)}</div> : <div className="mt-10 rounded-xl border border-dashed p-12 text-center"><h2 className="font-heading text-xl font-semibold">Proyek tidak ditemukan</h2><p className="mt-2 text-muted">Coba ubah kata kunci atau filter.</p><Button asChild variant="outline" className="mt-5"><Link href={route('projects.index')}>Reset filter</Link></Button></div>}<div className="mt-8 flex flex-wrap gap-2">{projects.links.map((link, index) => link.url ? <Link key={index} href={link.url} className={`rounded-md border px-3 py-2 text-sm ${link.active ? 'bg-primary text-primary-foreground' : ''}`} dangerouslySetInnerHTML={{ __html: link.label }} /> : null)}</div></section></PublicLayout>;
}
