import { Button } from '@/Components/ui/button';
import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, router } from '@inertiajs/react';
import { useState, type FormEvent } from 'react';

type Project = { id: number; title: string; slug: string; status: string; is_featured: boolean; category: { name: string } };
type Page = { data: Project[]; links: { url: string | null; label: string; active: boolean }[] };

export default function ProjectsIndex({ projects, filters }: { projects: Page; filters: { search?: string; status?: string } }) {
    const [search, setSearch] = useState(filters.search ?? ''); const [status, setStatus] = useState(filters.status ?? '');
    const submit = (event: FormEvent) => { event.preventDefault(); router.get(route('admin.projects.index'), { search, status }, { preserveState: true, replace: true }); };
    const remove = (project: Project) => { if (window.confirm(`Arsipkan proyek “${project.title}”?`)) router.delete(route('admin.projects.destroy', project.id)); };
    return <AdminLayout><Head title="Proyek" /><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-accent">Portfolio</p><h1 className="mt-1 font-heading text-3xl font-semibold">Proyek</h1></div><Button asChild><Link href={route('admin.projects.create')}>Tambah proyek</Link></Button></div><form onSubmit={submit} className="mt-6 flex flex-wrap gap-2"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari proyek..." className="min-h-10 min-w-64 flex-1 rounded-md border bg-surface px-3" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="min-h-10 rounded-md border bg-surface px-3"><option value="">Semua status</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><Button type="submit" variant="outline">Filter</Button></form><div className="mt-5 overflow-hidden rounded-lg border bg-surface"><div className="divide-y">{projects.data.map((project) => <div key={project.id} className="flex flex-wrap items-center justify-between gap-4 p-4"><div><div className="flex items-center gap-2"><h2 className="font-medium">{project.title}</h2>{project.is_featured && <span className="rounded-full bg-primary/15 px-2 py-0.5 text-xs text-primary">Unggulan</span>}</div><p className="mt-1 text-sm text-muted">{project.category.name} · {project.status}</p></div><div><Link href={route('admin.projects.edit', project.id)} className="text-sm text-accent">Edit</Link><button onClick={() => remove(project)} className="ms-4 text-sm text-destructive">Arsipkan</button></div></div>)}</div>{!projects.data.length && <p className="p-8 text-center text-muted">Belum ada proyek.</p>}</div><div className="mt-5 flex gap-2">{projects.links.map((link, i) => link.url ? <Link key={i} href={link.url} className={`rounded border px-3 py-2 text-sm ${link.active ? 'bg-primary text-primary-foreground' : ''}`} dangerouslySetInnerHTML={{ __html: link.label }} /> : null)}</div></AdminLayout>;
}
