server {
    listen 8080 default_server;
    server_name localhost 127.0.0.1;
    root "D:/ProjectPortofolio/public";

    index index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass php_upstream;
    }

    location ~ /\.ht {
        deny all;
    }
}
