import { SectionHeader } from '@/Components/public/SectionHeader';
import { Button } from '@/Components/ui/button';
import PublicLayout from '@/Layouts/PublicLayout';
import { mediaUrl } from '@/lib/media';
import { Head, Link } from '@inertiajs/react';

type Profile = { name: string; headline: string; about_description: string; profile_image?: string; location?: string; availability_text: string };
type Education = { id: number; institution: string; degree: string; study_program: string; start_year: number; end_year?: number; description?: string };
type SkillCategory = { id: number; name: string; description?: string; skills: { id: number; name: string; description?: string }[] };

export default function About({ profile, educations, skillCategories, stats }: { profile: Profile; educations: Education[]; skillCategories: SkillCategory[]; stats: Record<string, number> }) {
    return <PublicLayout><Head title={`Tentang — ${profile.name}`} /><section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="grid items-start gap-12 lg:grid-cols-[.75fr_1.25fr]"><img src={mediaUrl(profile.profile_image)} alt={`Foto ${profile.name}`} className="aspect-[4/5] w-full rounded-2xl border object-cover" /><div><p className="text-sm text-accent">Tentang saya</p><h1 className="mt-3 font-heading text-4xl font-semibold sm:text-5xl">{profile.headline}</h1><div className="mt-7 whitespace-pre-line text-lg leading-8 text-muted">{profile.about_description}</div><p className="mt-6 text-sm text-success">{profile.availability_text}</p><div className="mt-7 flex gap-3"><Button asChild><Link href={route('cv.show')}>Lihat CV</Link></Button><Button asChild variant="outline"><Link href={route('contact.create')}>Kontak</Link></Button></div></div></div><div className="mt-20 grid gap-4 sm:grid-cols-3">{Object.entries(stats).map(([label, value]) => <div key={label} className="rounded-xl border bg-surface p-6"><p className="font-heading text-4xl font-semibold text-primary">{value}</p><p className="mt-2 capitalize text-muted">{label}</p></div>)}</div></section><section className="bg-surface-secondary/50"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><SectionHeader eyebrow="Education" title="Pendidikan" /><div className="mt-8 grid gap-5 md:grid-cols-2">{educations.map((education) => <article key={education.id} className="rounded-xl border bg-surface p-6"><p className="text-sm text-accent">{education.start_year} — {education.end_year ?? 'Sekarang'}</p><h2 className="mt-3 font-heading text-xl font-semibold">{education.degree} {education.study_program}</h2><p className="mt-1 text-muted">{education.institution}</p>{education.description && <p className="mt-4 text-sm leading-6 text-muted">{education.description}</p>}</article>)}</div></div></section><section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><SectionHeader eyebrow="Expertise" title="Skill utama" /><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{skillCategories.map((category) => <article key={category.id} className="rounded-xl border bg-surface p-6"><h2 className="font-heading text-lg font-semibold">{category.name}</h2><div className="mt-4 flex flex-wrap gap-2">{category.skills.map((skill) => <span key={skill.id} title={skill.description} className="rounded-full bg-surface-secondary px-3 py-1.5 text-sm">{skill.name}</span>)}</div></article>)}</div></section></PublicLayout>;
}
