import InputError from '@/Components/InputError';
import { Button } from '@/Components/ui/button';
import PublicLayout from '@/Layouts/PublicLayout';
import { Head, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

type Profile = { email: string; location?: string; linkedin_url?: string; github_url?: string; availability_text: string };

export default function Contact({ profile }: { profile: Profile }) {
    const { data, setData, post, processing, errors, reset, recentlySuccessful } = useForm({ name: '', email: '', organization: '', subject: '', message: '', website: '' });
    const submit = (event: FormEvent) => { event.preventDefault(); post(route('contact.store'), { preserveScroll: true, onSuccess: () => reset() }); };
    return <PublicLayout><Head title="Kontak" /><section className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="text-sm text-accent">Get in touch</p><h1 className="mt-3 font-heading text-5xl font-semibold">Mari mulai percakapan</h1><p className="mt-5 text-lg leading-8 text-muted">{profile.availability_text}</p><dl className="mt-10 space-y-5"><div><dt className="text-xs uppercase tracking-wider text-muted">Email</dt><dd className="mt-1"><a href={`mailto:${profile.email}`} className="text-accent">{profile.email}</a></dd></div>{profile.location && <div><dt className="text-xs uppercase tracking-wider text-muted">Lokasi</dt><dd className="mt-1">{profile.location}</dd></div>}</dl><div className="mt-8 flex gap-4">{profile.linkedin_url && <a href={profile.linkedin_url} target="_blank" rel="noreferrer" className="text-sm text-accent">LinkedIn</a>}{profile.github_url && <a href={profile.github_url} target="_blank" rel="noreferrer" className="text-sm text-accent">GitHub</a>}</div></div><form onSubmit={submit} className="space-y-5 rounded-xl border bg-surface p-5 sm:p-8">{recentlySuccessful && <p className="rounded-md bg-success/10 p-3 text-sm text-success">Pesan berhasil disimpan.</p>}<div className="grid gap-5 sm:grid-cols-2"><Field name="name" label="Nama" value={data.name} onChange={(value) => setData('name', value)} error={errors.name} /><Field name="email" label="Email" type="email" value={data.email} onChange={(value) => setData('email', value)} error={errors.email} /></div><Field name="organization" label="Perusahaan atau instansi (opsional)" value={data.organization} onChange={(value) => setData('organization', value)} error={errors.organization} /><Field name="subject" label="Subjek" value={data.subject} onChange={(value) => setData('subject', value)} error={errors.subject} /><div className="space-y-2"><label htmlFor="message" className="text-sm font-medium">Pesan</label><textarea id="message" rows={7} value={data.message} onChange={(event) => setData('message', event.target.value)} className="block w-full rounded-md border bg-background px-3 py-2" /><InputError message={errors.message} /></div><div className="hidden" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" tabIndex={-1} autoComplete="off" value={data.website} onChange={(event) => setData('website', event.target.value)} /></div><Button type="submit" disabled={processing} className="w-full sm:w-auto">{processing ? 'Mengirim...' : 'Kirim pesan'}</Button></form></section></PublicLayout>;
}

function Field({ name, label, value, onChange, error, type = 'text' }: { name: string; label: string; value: string; onChange: (value: string) => void; error?: string; type?: string }) { return <div className="space-y-2"><label htmlFor={name} className="text-sm font-medium">{label}</label><input id={name} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="block min-h-11 w-full rounded-md border bg-background px-3" /><InputError message={error} /></div>; }
