import { SectionHeader } from '@/Components/public/SectionHeader';
import PublicLayout from '@/Layouts/PublicLayout';
import { mediaUrl } from '@/lib/media';
import { Head } from '@inertiajs/react';

type Experience = { id: number; position: string; organization: string; location?: string; logo?: string; start_date: string; end_date?: string; is_current: boolean; description: string; responsibilities?: string[]; technologies?: string[] };
type Education = { id: number; institution: string; degree: string; study_program: string; start_year: number; end_year?: number; description?: string; logo?: string };

export default function ExperiencePage({ experiences, educations }: { experiences: Experience[]; educations: Education[] }) {
    return <PublicLayout><Head title="Pengalaman" /><section className="mx-auto max-w-5xl px-4 py-20 sm:px-6"><SectionHeader eyebrow="Professional journey" title="Pengalaman" description="Perjalanan belajar, kolaborasi, dan penerapan kemampuan dalam proyek nyata." /><div className="mt-12 border-l border-border pl-7 sm:pl-10">{experiences.map((experience) => <article key={experience.id} className="relative pb-12"><span className="absolute -left-[34px] top-2 size-3 rounded-full border-2 border-primary bg-background sm:-left-[46px]" /><div className="rounded-xl border bg-surface p-5 sm:p-7"><div className="flex gap-4"><img src={mediaUrl(experience.logo)} alt={`Logo ${experience.organization}`} className="size-14 rounded-md border object-cover" /><div><p className="text-sm text-accent">{new Date(experience.start_date).toLocaleDateString('id-ID', { month: 'short', year: 'numeric' })} — {experience.is_current ? 'Sekarang' : experience.end_date ? new Date(experience.end_date).toLocaleDateString('id-ID', { month: 'short', year: 'numeric' }) : ''}</p><h2 className="mt-1 font-heading text-xl font-semibold">{experience.position}</h2><p className="text-muted">{experience.organization}{experience.location ? ` · ${experience.location}` : ''}</p></div></div><p className="mt-5 leading-7 text-muted">{experience.description}</p>{experience.responsibilities?.length ? <ul className="mt-5 list-disc space-y-2 pl-5 text-sm text-muted">{experience.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul> : null}<div className="mt-5 flex flex-wrap gap-2">{experience.technologies?.map((item) => <span key={item} className="rounded-full bg-surface-secondary px-3 py-1 text-xs">{item}</span>)}</div></div></article>)}</div></section><section className="bg-surface-secondary/40"><div className="mx-auto max-w-5xl px-4 py-20 sm:px-6"><SectionHeader eyebrow="Academic" title="Pendidikan" /><div className="mt-8 grid gap-5">{educations.map((education) => <article key={education.id} className="rounded-xl border bg-surface p-6"><p className="text-sm text-accent">{education.start_year} — {education.end_year ?? 'Sekarang'}</p><h2 className="mt-2 font-heading text-xl font-semibold">{education.degree} {education.study_program}</h2><p className="text-muted">{education.institution}</p>{education.description && <p className="mt-4 leading-7 text-muted">{education.description}</p>}</article>)}</div></div></section></PublicLayout>;
}
